### ISSUE TITLE
Craft 4 issue

### ISSUE THREAD

**Issue by sunscreem** [codemonauts/craft-time-field#1]
Hey.

Thanks for updating this for Craft 4.

I remove the old version prior to upgrading to Craft 4, now when I composer require the plugin I get this:

![image](https://user-images.githubusercontent.com/7523595/173245609-8f28a2aa-f86a-4d6e-885a-03aa2101683b.png)

On all backend and front end pages (but not the console)

**Comment by kringkaste** [comment]
Hi! I'm going to look at it now.

**Comment by kringkaste** [comment]
Hi @sunscreem , this attribute is removed in Craft4. So I'm not sure what other component try to set this. Can you send me the full stack trace? I need to know who started this.

**Comment by sunscreem** [comment]
Hey @kringkaste - Appreciate your help with this.

I've tried a few things. Caches cleared, removed and re-installed the vendor folder but it's still doing the same. 

I tried installing it on a clean install of version 4 and it seems to be working well.

<details>
<summary>
Here's the stack trace
</summary>

2022-06-14 11:59:44 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=builditconf;port=3306 {"memory":1535392} 
2022-06-14 11:59:44 [web.INFO] [yii\web\Session::open] Session started {"memory":3476424} 
2022-06-14 11:59:44 [web.INFO] [superbig\bugsnag\Bugsnag::init] Bugsnag plugin loaded {"memory":3955480} 
2022-06-14 11:59:44 [web.INFO] [leowebguy\mixmanifest\MixManifest::init] Mix Manifest plugin loaded {"memory":6046600} 
2022-06-14 11:59:44 [web.INFO] [nystudio107\retour\Retour::init] Retour plugin loaded {"memory":6358720} 
2022-06-14 11:59:44 [web.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":6892992} 
2022-06-14 11:59:44 [web.ERROR] [yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: codemonauts\timefield\fields\Time::columnType in /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#1 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#2 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct()
#3 [internal function]: craft\base\Model->__construct()
#4 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#5 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#6 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#7 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject()
#8 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/helpers/Component.php(121): Craft::createObject()
#9 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/services/Fields.php(593): craft\helpers\Component::createComponent()
#10 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/services/Fields.php(618): craft\services\Fields->createField()
#11 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/services/Fields.php(647): craft\services\Fields->_fields()
#12 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1935): craft\services\Fields->getAllFields()
#13 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1279): craft\elements\db\ElementQuery->customFields()
#14 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#15 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#16 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand()
#17 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/db/Query.php(180): yii\db\Query->one()
#18 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1450): craft\db\Query->one()
#19 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/elements/User.php(539): craft\elements\db\ElementQuery->one()
#20 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/web/User.php(697): craft\elements\User::findIdentity()
#21 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/web/User.php(489): yii\web\User->renewAuthStatus()
#22 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/web/User.php(198): craft\web\User->renewAuthStatus()
#23 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/web/Application.php(423): yii\web\User->getIdentity()
#24 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/web/Application.php(107): craft\web\Application->debugBootstrap()
#25 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#26 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#27 [internal function]: yii\base\Application->__construct()
#28 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#29 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#30 /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#31 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject()
#32 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/bootstrap/bootstrap.php(239): Craft::createObject()
#33 /home/forge/bic.sunscreem.xyz/vendor/craftcms/cms/bootstrap/web.php(40): require('...')
#34 /home/forge/bic.sunscreem.xyz/web/index.php(24): require('...')
#35 {main} {"memory":8816216,"exception":"[object] (yii\\base\\UnknownPropertyException(code: 0): Setting unknown property: codemonauts\\timefield\\fields\\Time::columnType at /home/forge/bic.sunscreem.xyz/vendor/yiisoft/yii2/base/Component.php:209)"} 
</details>

<details>
<summary>
And if it's any help here's the current info on plugin versions etc:
</summary>

![image](https://user-images.githubusercontent.com/7523595/173572885-2273051c-ddf1-4a2b-a1f5-14cac3b7abff.png)

</details>

**Comment by sunscreem** [comment]
Hey @kringkaste - is there anything else you need from me just now?

**Comment by kringkaste** [comment]
Is it right, that you have existing fields configured using this plugin when you try to install the plugin again? Can you send me the yaml from config/project/fields of one of that fields?

**Comment by sunscreem** [comment]
Hey @kringkaste - sure:

```yaml
columnSuffix: null
contentColumnType: string
fieldGroup: 25e3e360-81cf-4903-baa2-ec1b5f3c5072 # Conference
handle: startTime
instructions: ''
name: 'Start Time'
searchable: false
settings:
  columnType: string
translationKeyFormat: null
translationMethod: none
type: codemonauts\timefield\fields\Time
```

**Comment by kringkaste** [comment]
Ok, that's the point. You have to remove the both lines starting with "settings:" and "  columnType:". Then you have to `./craft project-config/touch` and `./craft project-config/apply` in the console. After this, you should be able to install the plugin again.

**Comment by sunscreem** [comment]
Brilliant. That's it now :) 

Thank you sir!
